---
provisioner:
  name: chef_zero

driver:
  name: vagrant

platforms:
- name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[rtorrent::default]
    attributes:
