---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  # - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[rtorrent::default]
    attributes:
